# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
publish_dcos_images_after: packer_build
tests_to_run:
  - test_composition.py
