# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
publish_dcos_images_after: never
run_framework_tests: false
run_integration_tests: false